-- YENI YOLCULUK - D1 Database Schema (v2)
CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, description TEXT, icon TEXT DEFAULT '📖', color TEXT DEFAULT '#4FACFE', sort_order INTEGER DEFAULT 0, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS articles (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, excerpt TEXT, content TEXT NOT NULL, category_id INTEGER, cover_image TEXT, tags TEXT, status TEXT DEFAULT 'draft', featured INTEGER DEFAULT 0, views INTEGER DEFAULT 0, shares INTEGER DEFAULT 0, og_title TEXT, og_description TEXT, og_image TEXT, reading_time INTEGER DEFAULT 0, created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')), FOREIGN KEY (category_id) REFERENCES categories(id));
CREATE TABLE IF NOT EXISTS roadmap_items (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, description TEXT, category TEXT NOT NULL, stage INTEGER NOT NULL, order_num INTEGER DEFAULT 0, status TEXT DEFAULT 'locked', icon TEXT DEFAULT '✨', created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS publications (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, excerpt TEXT, content TEXT NOT NULL, magazine_name TEXT NOT NULL, magazine_url TEXT, issue_number TEXT, publish_date TEXT, cover_image TEXT, pdf_url TEXT, category TEXT, tags TEXT, status TEXT DEFAULT 'published', views INTEGER DEFAULT 0, og_title TEXT, og_description TEXT, created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS admins (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role TEXT DEFAULT 'admin', created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT);
INSERT INTO categories (name, slug, description, icon, color, sort_order) VALUES ('Felsefe', 'felsefe', 'Düşüncenin derinliklerine yolculuk', '🦉', '#4FACFE', 1), ('Edebiyat', 'edebiyat', 'Kelimelerin ruhla buluşması', '📖', '#00C6FB', 2), ('Yol Haritası', 'yol-haritasi', 'Öğrenme ve keşif güzergahı', '🧭', '#667EEA', 3), ('Denemeler', 'denemeler', 'Özgür düşüncenin sahifeleri', '✍️', '#764BA2', 4), ('Dergiler', 'dergiler', 'Yayımlanan makaleler ve dergi yayınları', '📰', '#2196F3', 5);
INSERT INTO roadmap_items (title, description, category, stage, order_num, status, icon) VALUES ('Antik Yunan Felsefesi', 'Sokrates, Platon, Aristoteles ile başlayan düşünce yolculuğu', 'felsefe', 1, 1, 'active', '🏛️'), ('Orta Çağ Felsefesi', 'Skolastik düşünce ve inanç-felsefe diyaloğu', 'felsefe', 1, 2, 'locked', '⛪'), ('Rönesans ve Aydınlanma', 'Modern düşüncenin tohumları atılır', 'felsefe', 2, 1, 'locked', '🌅'), ('Alman İdealizmi', 'Kant, Hegel, Schopenhauer ile derinleşme', 'felsefe', 2, 2, 'locked', '🧠'), ('Varoluşçuluk', 'Kierkegaard, Sartre, Camus ile varoluşun anlamı', 'felsefe', 3, 1, 'locked', '🌌'), ('Postmodern Düşünce', 'Derrida, Foucault, Deleuze ile sınırları aşma', 'felsefe', 3, 2, 'locked', '🔮');
INSERT INTO roadmap_items (title, description, category, stage, order_num, status, icon) VALUES ('Divan Edebiyatı', 'Klasik Türk şiirinin zirveleri', 'edebiyat', 1, 1, 'active', '📜'), ('Tanzimat Edebiyatı', 'Modernleşme ve edebiyatın dönüşümü', 'edebiyat', 1, 2, 'locked', '📖'), ('Servet-i Fünun', 'Sanatın özerkliği ve estetik arayışlar', 'edebiyat', 2, 1, 'locked', '🌸'), ('Cumhuriyet Dönemi', 'Ulusal edebiyatın doğuşu ve gelişimi', 'edebiyat', 2, 2, 'locked', '🇹🇷'), ('Modern Türk Edebiyatı', 'Çağdaş anlatılar ve yeni biçimler', 'edebiyat', 3, 1, 'locked', '✨'), ('Dünya Klasikleri', 'Evrensel edebiyatın ufuk açıcı eserleri', 'edebiyat', 3, 2, 'locked', '🌍');
INSERT INTO settings (key, value) VALUES ('site_name', 'Yeni Yolculuk'), ('site_description', 'Felsefe ve edebiyatın buluştuğu dijital düşünce evreni'), ('site_author', 'Orçun Kundakcı'), ('site_url', 'https://orcunkundakci.com.tr'), ('social_twitter', '@orcunkundakci'), ('social_bluesky', 'orcunkundakci.bsky.social'), ('social_instagram', ''), ('social_linkedin', ''), ('social_github', ''), ('landing_mode', 'true');
